function uiscale(action);


% user function uiscale
% interactively allows user to set x axis scale and total size of y dimension of current figure

% indx values for handles stored with userdata
ih_fig = 1;
ih_x_scale = 2;
ih_y_scale = 3;
ih_cancel = 4;
ih_ok = 5;

if nargin<1,
  action='initialize';
end;

if strcmp(action,'initialize'),


%------------------------------------------
%set up default colors and stuff
%------------------------------------------
  titleColor=[0.8 0.8 0.8];
  btnColor=[0.7 0.7 0.7];
  labelColor=[0.5 0.5 0.5];
  consoleColor=[0.5 0.5 0.7];
  frmColor=[0.5 0.5 0.5];
  quitcolor=[0.5 0.5 0.5];
  labelWid=0.4;
  labelHt=0.1;
  btnWid=0.4;
  btnSpace=0.07;
  btnHt=0.2;
  frmBorder=0.03;

  %---------------------------------------------------------
  %set up the gui figure window
  %---------------------------------------------------------

  h_fig=watchon;
  h_dialog=figure(...
      'Visible', 'off',...
      'NumberTitle','off',...
      'Units','normalized',...
      'Position',[0.3,0.8,0.2,0.2],...
      'Menubar','none',...
      'Name','Scaling Dialog Box');
      axis('off');
      
      
  %------------------------------------------------------
  %  get values for display in scaling edit boxes
  %------------------------------------------------------

  [x_per_axis_inch, y_fig_inches] = get_scale_vals(h_fig)

  %------------------------------------------------------
  %  Scaling Dialog Box Frame
  %------------------------------------------------------
  frmPos=[frmBorder frmBorder 1-2*frmBorder 1-2*frmBorder];
  uicontrol(...
      'Style','frame',...
      'Units','normalized',...
      'Position',frmPos,...
      'BackgroundColor',frmColor);

  %-------------------------------------------------------
  %  The 'Axis Scaling' edit boxes
  %-------------------------------------------------------
  %scaling main label
  labelStr=['Axis Scaling'];
  labelPos=[3*frmBorder 1-3*frmBorder-1*labelHt 2*labelWid labelHt];
  uicontrol(...
      'Style','Text',...
      'Units','normalized',...
      'Position',labelPos,...
      'BackgroundColor',frmColor,...
      'HorizontalAlignment','center',...
      'String',labelStr);

  %x axis scaling label: "x:"
  labelStr=['x:'];
  labelPos=[3*frmBorder 1-3*frmBorder-2*labelHt .2*labelWid labelHt];
  uicontrol(...
      'Style','Text',...
      'Units','normalized',...
      'Position',labelPos,...
      'BackgroundColor',frmColor,...
      'HorizontalAlignment','center',...
      'String',labelStr);
  
  %x axis scaling label: "ms/in"
  labelStr=['ms/inch'];
  labelPos=[3*frmBorder+1.3*labelWid 1-3*frmBorder-2*labelHt .7*labelWid labelHt];
  uicontrol(...
      'Style','Text',...
      'Units','normalized',...
      'Position',labelPos,...
      'BackgroundColor',frmColor,...
      'HorizontalAlignment','center',...
      'String',labelStr);  

  %X axis scaling edit box
  labelStr=[num2str(x_per_axis_inch)];
  labelPos=[3*frmBorder+.2*labelWid 1-3*frmBorder-2*labelHt 1.1*labelWid labelHt];
  h_x_scale=uicontrol(...
      'Style','edit',...
      'Units','normalized',...
      'Position',labelPos,...
      'BackgroundColor',btnColor,...
      'String',labelStr,...
      'Callback','uiscale(''eval'')');

  %y axis scaling label: "y:"
  labelStr=['y:'];
  labelPos=[3*frmBorder 1-3*frmBorder-3.2*labelHt .2*labelWid labelHt];
  uicontrol(...
      'Style','Text',...
      'Units','normalized',...
      'Position',labelPos,...
      'BackgroundColor',frmColor,...
      'HorizontalAlignment','center',...
      'String',labelStr);
  
  %y axis scaling label: "units/in"
  labelStr=['inches'];
  labelPos=[3*frmBorder+1.3*labelWid 1-3*frmBorder-3.2*labelHt .7*labelWid labelHt];
  uicontrol(...
      'Style','Text',...
      'Units','normalized',...
      'Position',labelPos,...
      'BackgroundColor',frmColor,...
      'HorizontalAlignment','center',...
      'String',labelStr);  

  %Y axis scaling edit box
  labelStr=[num2str(y_fig_inches)];
  labelPos=[3*frmBorder+.2*labelWid 1-3*frmBorder-3.2*labelHt 1.1*labelWid labelHt];
  h_y_scale=uicontrol(...
      'Style','edit',...
      'Units','normalized',...
      'Position',labelPos,...
      'BackgroundColor',btnColor,...
      'String',labelStr,...
      'Callback','uiscale(''eval'')');
 
  %----------------------------------------------------------
  %  the 'Cancel' button
  %----------------------------------------------------------
  btnPos=[3*frmBorder 3*frmBorder (1-9*frmBorder)/2 btnHt];
  btnStr=['Cancel'];
  h_cancel=uicontrol(...
      'Style','pushbutton',...
      'Units','normalized',...
      'Position',btnPos,...
      'String',btnStr,...
      'BackgroundColor',btnColor,...
      'Callback','h_dialog=get(0,''pointerwindow'');close(h_dialog)');

  %----------------------------------------------------------
  %  the 'OK' button
  %----------------------------------------------------------
  btnPos=[6*frmBorder+(1-9*frmBorder)/2 3*frmBorder (1-9*frmBorder)/2 btnHt];
  btnStr=['OK'];
  h_ok=uicontrol(...
      'Style','pushbutton',...
      'Units','normalized',...
      'Position',btnPos,...
      'String',btnStr,...
      'BackgroundColor',btnColor,...
      'Callback','h_dialog=get(0,''pointerwindow''); figure(h_dialog); uiscale(''ok'')');

  %uncover the interface and store handles in userdata
  hndlList = [h_fig, h_x_scale, h_y_scale, h_cancel, h_ok];
  watchoff(h_fig);
  set(h_dialog,'Visible','on','UserData',hndlList);
  uiscale('eval');

  %----------------------------------------------------------------

elseif strcmp(action,'eval')
  %my what elegant programming! Of course one might sometime want something to happen here
  %perhaps update display as values are typed
  %then need to save and restore values in case of cancel

elseif strcmp(action,'ok')
  %get handle list
  h_dialog = gcf;
  hndlList=get(h_dialog,'UserData');
  %get desired scaling values from appropriate handles
  x_per_axis_inch = str2num(get(hndlList(ih_x_scale),'string'));
  y_fig_inches = str2num(get(hndlList(ih_y_scale),'string'));
  %set desired scaling values in figure
  set_scale_vals(hndlList(ih_fig), x_per_axis_inch, y_fig_inches); 
  %exit
  close(h_dialog);
 
end;
