function [] = mAutoLabel(batch,the_template,syll,thresh,FFTthresh,minCount,maxCount,refrac,chanSpec)
%
% script to autolabel syllables matching spectral template in batch of files. 
%
% mAutoLabel(batch,the_template,syll,thresh,FFTthresh.minCount)
%
% batch = batchfile of cbin files.
%
% the_template = 128x1 vector generated by tafsimtw() used as spectral
% template
%
% syll = what you want to label the detected syllables.
%
% thresh = amplitude threshold for segmentation.
%
% FFTthresh = threshold for template match. Estimate using uievtafsim()
%
% minCount = number of consequetive FFTthresh crossings for syll
% detection. Also estimated from uievtafsim()
%

mk_tempf(batch,the_template,2,chanSpec);

%min threshold
cntrng(1).MIN=minCount;
cntrng(1).MAX=maxCount;
%true/false logic, true->note=0
cntrng(1).NOT=0;
%evtafmode=1; birdtafmode=0;
cntrng(1).MODE=1;
%threshold
cntrng(1).TH=FFTthresh;
%and/or logic with other templates.
cntrng(1).AND=0;
cntrng(1).BTMIN=0;

% % % min threshold
% cntrng(2).MIN=minCount;
% cntrng(2).MAX=maxCount;
% % true/false logic, true->note=0
% cntrng(2).NOT=0;
% % evtafmode=1; birdtafmode=0;
% cntrng(2).MODE=1;
% % threshold
% cntrng(2).TH=FFTthresh;
% % and/or logic with other templates.
% cntrng(2).AND=0;
% cntrng(2).BTMIN=0;
% % 
% % % 
% % % min threshold
% cntrng(3).MIN=minCount;
% cntrng(3).MAX=maxCount;
% % true/false logic, true->note=0
% cntrng(3).NOT=0;
% % evtafmode=1; birdtafmode=0;
% cntrng(3).MODE=1;
% % threshold
% cntrng(3).TH=FFTthresh;
% % and/or logic with other templates.
% cntrng(3).AND=0;
% cntrng(3).BTMIN=0;
% 
% % % min threshold
% cntrng(4).MIN=minCount;
% cntrng(4).MAX=maxCount;
% % true/false logic, true->note=0
% cntrng(4).NOT=0;
% % evtafmode=1; birdtafmode=0;
% cntrng(4).MODE=1;
% % threshold
% cntrng(4).TH=FFTthresh;
% % and/or logic with other templates.
% cntrng(4).AND=0;
% cntrng(4).BTMIN=0;
% 
% % % min threshold
% cntrng(5).MIN=minCount;
% cntrng(5).MAX=maxCount;
% % true/false logic, true->note=0
% cntrng(5).NOT=0;
% % evtafmode=1; birdtafmode=0;
% cntrng(5).MODE=1;
% % threshold
% cntrng(5).TH=FFTthresh;
% % and/or logic with other templates.
% cntrng(5).AND=0;
% cntrng(5).BTMIN=0;




get_trigt2(batch,cntrng,refrac,128,1,1,chanSpec);
label_trigs(batch,syll,chanSpec,thresh,1,1,10,30,2);