function createfigure4B(cdata1)
%CREATEFIGURE4(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 11-Jun-2009 12:16:56

% Create figure
figure1 = figure('XVisual',...
    '0x26 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,...
    'YTickLabel',{'0','2000','4000','6000','8000','10000','12000'},...
    'YTick',[132 332 532 732 932 1132 1332],...
    'XTickLabel',{'0','20','40'},...
    'XTick',[0 160 320],...
    'Layer','top',...
    'CLim',[-0.03 0.03]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([0 400]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([0 1408]);
box('on');
hold('all');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create colorbar
colorbar('peer',axes1);

