function errorbarfigure(X1, Y1, L1, U1)
%CREATEFIGURE1(X1,Y1,L1,U1)
%  X1:  errorbar x
%  Y1:  errorbar y
%  L1:  errorbar l
%  U1:  errorbar u

%  Auto-generated by MATLAB on 25-Sep-2008 16:47:10

% Create figure
figure1 = figure;

% Create axes
axes('Parent',figure1,...
    'XTickLabel',{'927','928','929','930','1001','1002','1003','920','921','922','923','924','925','926','40  '},...
    'XTick',[0.5 2.5 4.5 6.5 8.5 10.5 12.5 14.5 16.5 18.5 20.5 22.5 24.5 26.5 28.5],...
    'XGrid','on');
% Uncomment the following line to preserve the X-limits of the axes
% xlim([0.5 40]);
hold('all');

% Create errorbar
errorbar(X1,Y1,L1,U1,'MarkerSize',10,'Marker','.','LineStyle',':',...
    'LineWidth',2,...
    'Color',[0 0 1]);

% Create title
title({'20th prctile; median; 80th prctile'});

