function createfigure1(YMatrix1)
%CREATEFIGURE1(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 27-May-2009 15:31:50

% Create figure
figure1 = figure('XVisual',...
    '0x26 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'0','-10','-20','-30','-40','-50','-60','10','20','30','40','50','60'},...
    'XTick',[700 620 540 460 380 300 220 780 860 940 1020 1100 1180]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([98.19 1339]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([-0.001184 1.099]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'MarkerSize',2,'Marker','*','LineStyle','none',...
    'Parent',axes1);
set(plot1(1),'Color',[0 0 1]);
set(plot1(2),'Color',[0 0.5 0]);
set(plot1(3),'Color',[1 0 0]);
set(plot1(4),'Color',[0 0.75 0.75]);
set(plot1(5),'Color',[0.75 0 0.75]);
set(plot1(6),'Color',[0.75 0.75 0]);
set(plot1(7),'Color',[0.25 0.25 0.25]);
set(plot1(8),'LineWidth',2,'Color',[0 0 1]);
set(plot1(9),'Color',[0 0.5 0]);
set(plot1(10),'Color',[1 0 0]);
set(plot1(11),'Color',[0 0.75 0.75]);
set(plot1(12),'Color',[0.75 0 0.75]);
set(plot1(13),'Color',[0.75 0.75 0]);
set(plot1(14),'Color',[0.25 0.25 0.25]);
set(plot1(15),'Color',[0 0 1]);
set(plot1(16),'Color',[0 0.5 0]);
set(plot1(17),'Color',[1 0 0]);
set(plot1(18),'Color',[0 0.75 0.75]);
set(plot1(19),'Color',[0.75 0 0.75]);
set(plot1(20),'Color',[0.75 0.75 0]);
set(plot1(21),'Color',[0.25 0.25 0.25]);
set(plot1(22),'Color',[0 0 1]);
set(plot1(23),'Color',[0 0.5 0]);
set(plot1(24),'Color',[1 0 0]);
set(plot1(25),'Color',[0 0.75 0.75]);
set(plot1(26),'Color',[0.75 0 0.75]);
set(plot1(27),'Color',[0.75 0.75 0]);
set(plot1(28),'Color',[0.25 0.25 0.25]);
set(plot1(29),'Marker','+','Color',[0.502 0.502 0.502],'MarkerSize',6);

